"""initial production schema

Revision ID: d84ace447e4c
Revises: 
Create Date: 2026-09-26 03:09:23.683487
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd84ace447e4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('recipients_count', sa.Integer(), nullable=False),
    sa.Column('cbsri', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('donations_count', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('notifications_30d', sa.Integer(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_blood_group'), 'donors', ['blood_group'], unique=False)
    op.create_index(op.f('ix_donors_district'), 'donors', ['district'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('safety_stock_units', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_blood_group'), 'inventory', ['blood_group'], unique=False)
    op.create_index(op.f('ix_inventory_district'), 'inventory', ['district'], unique=False)
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_district'), 'blood_requests', ['district'], unique=False)
    op.create_index(op.f('ix_blood_requests_donor_id'), 'blood_requests', ['donor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donor_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_blood_requests_donor_id'), table_name='blood_requests')
    op.drop_index(op.f('ix_blood_requests_district'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index(op.f('ix_inventory_district'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_blood_group'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_donors_district'), table_name='donors')
    op.drop_index(op.f('ix_donors_blood_group'), table_name='donors')
    op.drop_table('donors')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
